// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const barExists = `-- name: BarExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            bar
        where
            id = $id
    )
`

func (q *Queries) BarExists(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, barExists)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
