// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
	"errors"
	"io"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const identicalTable = `-- name: IdenticalTable :many
SELECT id FROM foo
`

func (q *Queries) IdenticalTable(ctx context.Context, opts ...query.ExecuteOption) ([]string, error) {
	result, err := q.db.QueryResultSet(ctx, identicalTable, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []string
	for {
		row, err := result.NextRow(ctx)
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var id string
		if err := row.Scan(&id); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, id)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}
