// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
	"errors"
	"io"

	"github.com/ydb-platform/ydb-go-sdk/v3/pkg/xerrors"
	"github.com/ydb-platform/ydb-go-sdk/v3/query"
)

const castCoalesce = `-- name: CastCoalesce :many
SELECT COALESCE(bar, '') AS login
FROM foo
`

func (q *Queries) CastCoalesce(ctx context.Context, opts ...query.ExecuteOption) ([]string, error) {
	result, err := q.db.QueryResultSet(ctx, castCoalesce, opts...)
	if err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	var items []string
	for {
		row, err := result.NextRow(ctx)
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		var login string
		if err := row.Scan(&login); err != nil {
			return nil, xerrors.WithStackTrace(err)
		}
		items = append(items, login)
	}
	if err := result.Close(ctx); err != nil {
		return nil, xerrors.WithStackTrace(err)
	}
	return items, nil
}
